calculate vector norm


In [4]:
import numpy as np
arr=np.array([1,-2,3,4])
for i in range(5):

    norm1=np.linalg.norm(arr,i)
    print(norm1)

4.0
10.0
5.477225575051661
4.641588833612778
4.337613136533361


calculate matrix determinant 

In [11]:
matx1=np.array([[1,2,3],[4,5,6],[7,8,9]])
det_matx1=np.linalg.det(matx1)
print(int(det_matx1))

0


calculate matrix inverse

In [18]:
def check_inv(matx):
    return matx.shape[0]==matx.shape[1] and np.linalg.det(matx)!=0


A=np.array([[1,2,3],[3,4,5],[1,2,6]])
A_inverse=np.linalg.inv(A)
print(A_inverse)
print(check_inv(A_inverse))

[[-2.33333333  1.          0.33333333]
 [ 2.16666667 -0.5        -0.66666667]
 [-0.33333333  0.          0.33333333]]
True


eigenvale and eigenvector

In [21]:
a=np.array([[1,2],[3,4]])
w,v=np.linalg.eig(a)
print(w[0])
print(v[0])

-0.3722813232690143
[-0.82456484 -0.41597356]


In [5]:
import pandas as pd
df=pd.read_csv('data1.csv')
print(df)

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%


get duuplicates across all columns

In [9]:
duplicate=df.duplicated()

print(duplicate)
print(df[duplicate])

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
dtype: bool
   Duration  Pulse  Maxpulse  Calories Precentage
3        60    100       120     300.0        60%


In [15]:
column_name=df.columns
duplicaes=df.duplicated(subset=column_name[1],keep=False)
duplicaes

0    False
1    False
2     True
3     True
4    False
5    False
6    False
7     True
8    False
dtype: bool

sorting by giveing the sort_values method the column you want to sort upon

In [20]:
df.sort_values(df.columns[1],ascending=False)

Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
8        60    111       138     400.0        60%
4        45    104       129     266.0        45%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
7        60    100       122     329.4        60%
6        60     98       126     286.0        60%
5        45     90       112     180.1        45%

remove duplicates

In [45]:
import pandas as pd
df=pd.read_csv('data1.csv')
print(df)

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%


In [50]:
x=df.drop_duplicates(df.columns[0],keep="first",inplace=False)
print(df)
print(x)

   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
1        60    102       127     300.0        60%
2        60    100       120     300.0        60%
3        60    100       120     300.0        60%
4        45    104       129     266.0        45%
5        45     90       112     180.1        45%
6        60     98       126     286.0        60%
7        60    100       122     329.4        60%
8        60    111       138     400.0        60%
   Duration  Pulse  Maxpulse  Calories Precentage
0        60    114       140     415.0        60%
4        45    104       129     266.0        45%


read from excel file
and accese row and columns via loc method

In [60]:
df1=pd.read_excel('presidents_names.xlsx')
print(df1)
print(df1.loc[[1,3],[df1.columns[0],df1.columns[1]]])

             Name       born  in office  in office.1
0    Jimmy C@rter 2024-01-10       1977       1981.0
1    Donald Trump 1946-06-14       2017          NaN
2  George W. Bush 1946-07-06       2001       2009.0
3    Bill Clinton 1946-08-19       1993       2001.0
4    Barack Obama 1961-08-04       2009       2017.0
           Name       born
1  Donald Trump 1946-06-14
3  Bill Clinton 1946-08-19


In [66]:
with pd.ExcelFile('presidents_names.xlsx') as xls:
    df1=pd.read_excel(xls,'Sheet1')
    print(df1[0:2][df1.columns[0:2]])
    df2=pd.read_excel(xls,'Sheet2')
    print(df2[0:2][df2.columns[0:2]])

FileNotFoundError: [Errno 2] No such file or directory: 'Sheet1'