In [3]:
import pandas as pd
#lapble encoding
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
#all models
#random forest
from sklearn.ensemble import RandomForestClassifier
#decision tree
from sklearn.tree import DecisionTreeClassifier
#svm
from sklearn.svm import SVC
#knn
from sklearn.neighbors import KNeighborsClassifier
#naive bayes
from sklearn.naive_bayes import GaussianNB



from sklearn.metrics import accuracy_score


In [4]:
df=pd.read_csv('titanic.csv')  
# leve only(Embarked,Gender,servived)
encoded_data=df[['Embarked','Gender']]
df.drop(['Embarked','Gender'],axis=1,inplace=True)
#encoding
le=LabelEncoder()
encoded_data['Embarked']=le.fit_transform(encoded_data['Embarked'])
encoded_data['Gender']=le.fit_transform(encoded_data['Gender']  )
#merging
df=pd.concat([df,encoded_data],axis=1)
df.drop(['Name','Ticket','Cabin'],axis=1,inplace=True)
#filling missing values
df['Age'].fillna(df['Age'].mean(),inplace=True)
df.isnull().sum()


C:\Users\mahmoud\AppData\Local\Temp\ipykernel_9276\1628471396.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  encoded_data['Embarked']=le.fit_transform(encoded_data['Embarked'])
C:\Users\mahmoud\AppData\Local\Temp\ipykernel_9276\1628471396.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  encoded_data['Gender']=le.fit_transform(encoded_data['Gender']  )
C:\Users\mahmoud\AppData\Local\Temp\ipykernel_9276\1628471396.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series thr

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Survived       0
Embarked       0
Gender         0
dtype: int64

In [5]:
x=df.drop('Survived',axis=1)
y=df['Survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [6]:
#random forest
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print("random forest accuracy",accuracy_score(y_test,y_pred))
#decision tree
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print("decision tree accuracy",accuracy_score(y_test,y_pred))
#svm
kernals=['linear','poly','rbf']
for k in kernals:
    svm=SVC(kernel=k)   
    svm.fit(x_train,y_train)
    y_pred=svm.predict(x_test)
    print(f"svm accuracy of kernala{k}",accuracy_score(y_test,y_pred))

#knn
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("knn accuracy",accuracy_score(y_test,y_pred))
#naive bayes
nb=GaussianNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
print("naive bayes accuracy",accuracy_score(y_test,y_pred))


random forest accuracy 0.8435754189944135
decision tree accuracy 0.7821229050279329
svm accuracy of kernalalinear 0.7877094972067039
svm accuracy of kernalapoly 0.6480446927374302
svm accuracy of kernalarbf 0.659217877094972
knn accuracy 0.6368715083798883
naive bayes accuracy 0.7877094972067039


In [31]:
import numpy as np
#2*3 matrix
# 3rows and 2 columns
A=np.array([[1,2],[3,4],[5,6]])
#2 rows and 3 columns
B=np.array([[1,2,3],[4,5,6]])
#3 rows and 3 columns
C=np.array([[1,2,3],[4,5,6],[7,8,9]])
#mul of A and B
print(A.dot(B))
# #mul of A and C
# print(A.dot(C))
#mul of B and C
print(B.dot(C))
#AB-BC
print(A.dot(B)-B.dot(C))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[30 36 42]
 [66 81 96]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 