Numpy libaray

In [1]:
import numpy as np

vertical and horizontal vectors

In [13]:
v1=np.array([2,3,5])
v2=np.array([[2],[3],[5]])
print(v1)
print(v1.shape,"\n")

print(v2)
print(v2.shape,"\n")


[2 3 5]
(3,) 

[[2]
 [3]
 [5]]
(3, 1) 



In [15]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


reshaping list from arange()to array 

In [25]:
list1=np.arange(0,16,1)
print(list1)
arr=np.array(list1.reshape(8,2))
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
